######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 2 17:03:56 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ModelView.h
SOURCES += main.cpp ModelView.cpp
